name: Generate project documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  job_generate_doc:
    name: Generate project documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:v3.22.1

    steps:
      - name: Clone
        uses: actions/checkout@v4.1.5

      - name: HTML documentation
        run: doxygen .doxygen/Doxyfile

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: app-solar-docs
          path: doc/html
