name: Unit testing with Codecov coverage checking

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  job_unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:3.22.1

    steps:
      - name: Clone
        uses: actions/checkout@v4.1.5

      - name: Build unit tests
        run: |
          cd tests/unit-tests/
          cmake -Bbuild -H. && make -C build && make -C build test

      - name: Generate code coverage
        run: |
          cd tests/unit-tests/
          lcov --directory . -b "$(realpath build/)" --capture --initial -o coverage.base && \
          lcov --rc lcov_branch_coverage=1 --directory . -b "$(realpath build/)" --capture -o coverage.capture && \
          lcov --directory . -b "$(realpath build/)" --add-tracefile coverage.base --add-tracefile coverage.capture -o coverage.info && \
          lcov --directory . -b "$(realpath build/)" --remove coverage.info '*/unit-tests/*' -o coverage.info && \
          genhtml coverage.info -o coverage

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: code-coverage
          path: tests/unit-tests/coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4.4.0
        with:
          fail_ci_if_error: true
          files: ./tests/unit-tests/coverage.info
          flags: unittests
          name: codecov-app-solar
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

